@Back_HostAddress = http://localhost:5237

POST {{Back_HostAddress}}/Tarea
Content-Type: application/json
Accept: application/json

{
    "NombreTarea": "Tarea de prueba",
    "Descripcion": "Esta es una tarea de prueba para verificar el funcionamiento del endpoint de agregar tarea",
    "Prioridad": "Alta",
    "Status": "Pendiente"  
}

###
