@Back_HostAddress = http://localhost:5237

POST {{Back_HostAddress}}/Tarea
Content-Type: application/json
Accept: application/json

{
    "NombreTarea": "Tarea de prueba 2",
    "DescripcionTarea": "2 Esta es una tarea de prueba para verificar el funcionamiento del endpoint de agregar tarea",
    "Prioridad": "Media",
    "Estatus": "Pendiente"  
}

###


PATCH {{Back_HostAddress}}/Tarea/2
Content-Type: application/json

{
    "estatus"  : "Completado"
} 
